### ISSUE TITLE
Code-Highlight in Slides does not disploy properly on Chrome.

### ISSUE THREAD

**Issue by Magolor** [Molunerfinn/hexo-theme-melody#218] opened 2019-08-07 04:03 UTC
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version: v1.5.6**

**Platform: Windows**

**Browser: Chrome**

## Expected behavior 

![](https://i.ibb.co/7tQtwwm/TIM-20190807115343.png)

Black background and Code Highlighting are Expected.

## Actual behavior 

![](https://i.ibb.co/GtHZmFQ/TIM-20190807115409.png)

While the background is transparent and there is no Highlighting(No matter what language is used).

Tested on different computers, none of them is displaying well.

The whole page is [here](https://magolor.cn/2019/08/06/data_structures/).

## Steps to reproduce the behavior 

I temporarily put the `.md` file of this page at [here](https://magolor.cn/files/data_structures.txt)

## Feature Request

---

**Comment by Molunerfinn** [comment] 2019-08-08 07:25
OK, the problem will be solved soon.

**Comment by Molunerfinn** [comment] 2019-08-08 07:50
After using your markdown file, I can't reproduce your situation:

![image](https://user-images.githubusercontent.com/12621342/62684938-4ad2d280-b9f4-11e9-8d4e-d6c53811f82c.png)

**Comment by Molunerfinn** [comment] 2019-08-08 08:04
I found that your blog's hljs has something different:

![image](https://user-images.githubusercontent.com/12621342/62685645-a3ef3600-b9f5-11e9-98bc-4db86624b0fc.png)

the `hljs.initHighlighting.called` is `undefined` while the right value is `true`:

![image](https://user-images.githubusercontent.com/12621342/62685715-c84b1280-b9f5-11e9-84a3-49e3b16674a8.png)

So your blog's hljs wasn't called. That's wried.

**Comment by Molunerfinn** [comment] 2019-08-08 09:05
OK, you can change to the branch `fix-218` to see if the fix can solve your problem.

```
cd hexo-theme-melody
git fetch
git checkout fix-218
```

**Comment by Molunerfinn** [comment] 2019-08-08 09:10
if the fix can solve your problem, then the branch will be merged to `dev` branch.

**Comment by Magolor** [comment] 2019-08-08 09:59
> if the fix can solve your problem, then the branch will be merged to `dev` branch.

Sorry, not working.

Well, this problem happens only on Chrome but not IE or Edge. And while running on `localhost` its behavior is expected(even on Chrome).

**Comment by Molunerfinn** [comment] 2019-08-08 10:05
So something happened when deploying online. Maybe the PWA plugin?
You can remove some plugins settings to see what happened.
And you can change the time to more than `0` (for example `1000` means 1s)to see if it could help:

https://github.com/Molunerfinn/hexo-theme-melody/blob/fix-218/layout/includes/slide/script.pug#L34

**Comment by Molunerfinn** [comment] 2019-08-08 10:11
Sorry but your page is not the newest:
![image](https://user-images.githubusercontent.com/12621342/62694888-c8540e00-ba07-11e9-8eaa-fba173b71455.png)
![image](https://user-images.githubusercontent.com/12621342/62694915-d9048400-ba07-11e9-9d08-c0f080971013.png)
The newest code is the following:

![image](https://user-images.githubusercontent.com/12621342/62694951-e883cd00-ba07-11e9-8f77-7fa8ee03a6cb.png)

**Comment by Magolor** [comment] 2019-08-08 10:23
> Sorry but your page is not the newest:
> ![image](https://user-images.githubusercontent.com/12621342/62694888-c8540e00-ba07-11e9-8eaa-fba173b71455.png)
> ![image](https://user-images.githubusercontent.com/12621342/62694915-d9048400-ba07-11e9-9d08-c0f080971013.png)
> The newest code is the following:
> 
> ![image](https://user-images.githubusercontent.com/12621342/62694951-e883cd00-ba07-11e9-8f77-7fa8ee03a6cb.png)

Fixed! Thank you so much!

Sorry for my silly mistake.

**Closed** 2019-08-08 11:31 UTC
